personal_management:
  target: dev

  outputs:
    dev:
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET_NAME') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('DBT_BIGQUERY_KEYPATH') }}"
      location: "{{ env_var('DBT_GCP_BIGQUERY_LOCATION') }}"
      method: service-account
      priority: interactive
      project: "{{ env_var('DBT_GCP_PROJECT_NAME') }}"
      threads: 1
      type: bigquery
