sources:
  - name: bronze
    schema: bronze  
    tables:
      - name: raw_notas_atributos
      - name: raw_notas_tarefas
      - name: raw_notas_nutricao
      - name: raw_notas_introspeccao

      - name: raw_notas_nutricao_enriquecida
      - name: raw_notas_atributos_enriquecido
