services:
  airflow:
    build: .

    container_name: airflow-personal-management
    command: standalone
    restart: unless-stopped

    ports:
      - "8080:8080"

    cpus: 1.0
    mem_limit: 2g

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 120
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW__API__WORKERS: 1

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./warehouse:/opt/airflow/warehouse
      - ./scripts:/opt/airflow/scripts
      - ./dbt:/opt/airflow/dbt
      - ${NOTES_FOLDER}:/opt/airflow/data/notes
      - ${BQ_CREDENTIAL_FILE}:/opt/airflow/keys/airflow-sa-key.json:ro
      - ./airflow-home:/root/airflow
