name: CI

on:
  push:
    branches: [main]

  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create required directories
        run: mkdir -p warehouse logs data

      - name: Install dependencies
        run: pip install apache-airflow ruff && pip install -r requirements.txt

      - name: Initializing DB
        run: python -c "import duckdb; con = duckdb.connect('warehouse/database.duckdb'); con.close()"

      - name: Lint DAGs
        run: ruff check dags/

      - name: Validate DAGs parse correctly
        run: python -c "from airflow.models import DagBag; db = DagBag('dags/'); assert not db.import_errors, db.import_errors"

      - name: Install dbt
        run: pip install dbt-core dbt-duckdb

      - name: Dbt compile
        working-directory: ./dbt
        run: dbt compile --profiles-dir .

      - name: Build Docker image
        run: docker build -t airflow-personal .

      - name: Install SQLFluff
        run: pip install sqlfluff sqlfluff-templater-dbt

      - name: Lint SQL files
        run: sqlfluff lint dbt/models/ --dialect duckdb
